### ISSUE TITLE
Need map in summary display

### ISSUE THREAD

**Issue by njarboe** [earthref/KArAr#1]
![Screen Shot 2022-06-09 at 10 52 07 AM](https://user-images.githubusercontent.com/1278789/172949855-96061db2-f9c6-4a7b-ac35-735b57e9df36.png)

**Comment by rminnett** [comment]
![image](https://user-images.githubusercontent.com/1182698/172998708-fb355063-6de9-407a-bd42-56dd38d0965d.png)
