### ISSUE TITLE
No Partition Coefficient Data label is not applicable to KArAr

### ISSUE THREAD

**Issue by njarboe** [earthref/KArAr#2]
![Screen Shot 2022-06-09 at 10 52 07 AM](https://user-images.githubusercontent.com/1278789/172950047-522af546-f035-4f69-88df-075ecff8e531.png)

**Comment by rminnett** [comment]
![image](https://user-images.githubusercontent.com/1182698/172998768-0287422d-0f17-4d3a-af63-44598a9965c9.png)
